using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SMSActivate_Net.API.JsonResponses;
using System.Collections.Concurrent;

namespace SMSActivate_Net.API.Extensions
{
    public class ServiceItem
    {
        public string Code { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
    }
    public class ServiceItemPrice : ServiceItem
    {
        public int Cost { get; set; }
        public int Count { get; set; }
    }

    public class ServiceItemHelper
    {
        private static ConcurrentDictionary<string, ServiceItem> services;
        static ServiceItemHelper()
        {
            services = new ConcurrentDictionary<string, ServiceItem>(StringComparer.OrdinalIgnoreCase);
            InitializeServices();
        }

        private static void InitializeServices()
        {
            services.TryAdd("ot", new ServiceItem { Code = "ot", Name = "Any other" });
            services.TryAdd("full", new ServiceItem { Code = "full", Name = "Full Rent" });
            services.TryAdd("fg", new ServiceItem { Code = "fg", Name = "IndianOil" });
            services.TryAdd("fr", new ServiceItem { Code = "fr", Name = "Dana" });
            services.TryAdd("wv", new ServiceItem { Code = "wv", Name = "AIS" });
            services.TryAdd("vm", new ServiceItem { Code = "vm", Name = "OkCupid" });
            services.TryAdd("dk", new ServiceItem { Code = "dk", Name = "Pairs" });
            services.TryAdd("mb", new ServiceItem { Code = "mb", Name = "Yahoo" });
            services.TryAdd("qg", new ServiceItem { Code = "qg", Name = "MoneyPay" });
            services.TryAdd("jt", new ServiceItem { Code = "jt", Name = "TurkiyePetrolleri" });
            services.TryAdd("bi", new ServiceItem { Code = "bi", Name = "勇仕网络Ys4fun" });
            services.TryAdd("pm", new ServiceItem { Code = "pm", Name = "AOL" });
            services.TryAdd("sv", new ServiceItem { Code = "sv", Name = "Dostavista" });
            services.TryAdd("pg", new ServiceItem { Code = "pg", Name = "NRJ Music Awards" });
            services.TryAdd("yz", new ServiceItem { Code = "yz", Name = "Около" });
            services.TryAdd("vo", new ServiceItem { Code = "vo", Name = "Brand20ua" });
            services.TryAdd("he", new ServiceItem { Code = "he", Name = "Mewt" });
            services.TryAdd("xg", new ServiceItem { Code = "xg", Name = "FortunaSK" });
            services.TryAdd("vk", new ServiceItem { Code = "vk", Name = "vk.com" });
            services.TryAdd("oj", new ServiceItem { Code = "oj", Name = "LoveRu" });
            services.TryAdd("gk", new ServiceItem { Code = "gk", Name = "AptekaRU" });
            services.TryAdd("qp", new ServiceItem { Code = "qp", Name = "Максавит" });
            services.TryAdd("sy", new ServiceItem { Code = "sy", Name = "Brahma" });
            services.TryAdd("ch", new ServiceItem { Code = "ch", Name = "Pocket52" });
            services.TryAdd("ia", new ServiceItem { Code = "ia", Name = "Socios" });
            services.TryAdd("bx", new ServiceItem { Code = "bx", Name = "Dosi" });
            services.TryAdd("ua", new ServiceItem { Code = "ua", Name = "BlaBlaCar" });
            services.TryAdd("xl", new ServiceItem { Code = "xl", Name = "Wmaraci" });
            services.TryAdd("qc", new ServiceItem { Code = "qc", Name = "Праймериз 2020" });
            services.TryAdd("rq", new ServiceItem { Code = "rq", Name = "AptekiPlus" });
            services.TryAdd("kt", new ServiceItem { Code = "kt", Name = "KakaoTalk" });
            services.TryAdd("bs", new ServiceItem { Code = "bs", Name = "TradeUP" });
            services.TryAdd("jr", new ServiceItem { Code = "jr", Name = "Самокат" });
            services.TryAdd("ii", new ServiceItem { Code = "ii", Name = "CashKaro" });
            services.TryAdd("rl", new ServiceItem { Code = "rl", Name = "inDriver" });
            services.TryAdd("nk", new ServiceItem { Code = "nk", Name = "Gittigidiyor" });
            services.TryAdd("hc", new ServiceItem { Code = "hc", Name = "MOMO" });
            services.TryAdd("ik", new ServiceItem { Code = "ik", Name = "GuruBets" });
            services.TryAdd("lj", new ServiceItem { Code = "lj", Name = "Santander" });
            services.TryAdd("rj", new ServiceItem { Code = "rj", Name = "Детский мир" });
            services.TryAdd("bn", new ServiceItem { Code = "bn", Name = "Alfagift" });
            services.TryAdd("dd", new ServiceItem { Code = "dd", Name = "CloudChat" });
            services.TryAdd("hy", new ServiceItem { Code = "hy", Name = "Ininal" });
            services.TryAdd("wf", new ServiceItem { Code = "wf", Name = "YandexGo" });
            services.TryAdd("jv", new ServiceItem { Code = "jv", Name = "Consultant" });
            services.TryAdd("ke", new ServiceItem { Code = "ke", Name = "Эльдорадо" });
            services.TryAdd("nn", new ServiceItem { Code = "nn", Name = "Giftcloud" });
            services.TryAdd("te", new ServiceItem { Code = "te", Name = "eFood" });
            services.TryAdd("av", new ServiceItem { Code = "av", Name = "avito" });
            services.TryAdd("zf", new ServiceItem { Code = "zf", Name = "OnTaxi" });
            services.TryAdd("zr", new ServiceItem { Code = "zr", Name = "Papara" });
            services.TryAdd("mu", new ServiceItem { Code = "mu", Name = "MyMusicTaste" });
            services.TryAdd("no", new ServiceItem { Code = "no", Name = "Virgo" });
            services.TryAdd("cc", new ServiceItem { Code = "cc", Name = "Quipp" });
            services.TryAdd("zm", new ServiceItem { Code = "zm", Name = "OfferUp" });
            services.TryAdd("vv", new ServiceItem { Code = "vv", Name = "Seosprint" });
            services.TryAdd("mo", new ServiceItem { Code = "mo", Name = "Bumble" });
            services.TryAdd("wg", new ServiceItem { Code = "wg", Name = "Skout" });
            services.TryAdd("tr", new ServiceItem { Code = "tr", Name = "Paysend" });
            services.TryAdd("zj", new ServiceItem { Code = "zj", Name = "ROBINHOOD" });
            services.TryAdd("ee", new ServiceItem { Code = "ee", Name = "Twilio" });
            services.TryAdd("fk", new ServiceItem { Code = "fk", Name = "BLIBLI" });
            services.TryAdd("ad", new ServiceItem { Code = "ad", Name = "Iti" });
            services.TryAdd("sl", new ServiceItem { Code = "sl", Name = "СберАптека" });
            services.TryAdd("fl", new ServiceItem { Code = "fl", Name = "RummyLoot" });
            services.TryAdd("hs", new ServiceItem { Code = "hs", Name = "Asda" });
            services.TryAdd("bl", new ServiceItem { Code = "bl", Name = "BIGO LIVE" });
            services.TryAdd("zx", new ServiceItem { Code = "zx", Name = "CommunityGaming" });
            services.TryAdd("gy", new ServiceItem { Code = "gy", Name = "MIYACHAT" });
            services.TryAdd("jq", new ServiceItem { Code = "jq", Name = "Paysafecard" });
            services.TryAdd("kp", new ServiceItem { Code = "kp", Name = "HQ Trivia" });
            services.TryAdd("ge", new ServiceItem { Code = "ge", Name = "Paytm" });
            services.TryAdd("gz", new ServiceItem { Code = "gz", Name = "LYKA" });
            services.TryAdd("mj", new ServiceItem { Code = "mj", Name = "Zalo" });
            services.TryAdd("ir", new ServiceItem { Code = "ir", Name = "Chispa" });
            services.TryAdd("fa", new ServiceItem { Code = "fa", Name = "XadrezFeliz" });
            services.TryAdd("at", new ServiceItem { Code = "at", Name = "Perfluence" });
            services.TryAdd("qh", new ServiceItem { Code = "qh", Name = "Oriflame" });
            services.TryAdd("dr", new ServiceItem { Code = "dr", Name = "OpenAI" });
            services.TryAdd("rg", new ServiceItem { Code = "rg", Name = "Porbet" });
            services.TryAdd("ih", new ServiceItem { Code = "ih", Name = "TeenPattiStarpro" });
            services.TryAdd("hk", new ServiceItem { Code = "hk", Name = "4Fun" });
            services.TryAdd("bm", new ServiceItem { Code = "bm", Name = "MarketGuru" });
            services.TryAdd("gs", new ServiceItem { Code = "gs", Name = "SamsungShop" });
            services.TryAdd("qv", new ServiceItem { Code = "qv", Name = "Badoo" });
            services.TryAdd("sr", new ServiceItem { Code = "sr", Name = "Starbucks" });
            services.TryAdd("ci", new ServiceItem { Code = "ci", Name = "redBus" });
            services.TryAdd("ac", new ServiceItem { Code = "ac", Name = "DoorDash" });
            services.TryAdd("sf", new ServiceItem { Code = "sf", Name = "SneakersnStuff" });
            services.TryAdd("ne", new ServiceItem { Code = "ne", Name = "Coindcx" });
            services.TryAdd("sm", new ServiceItem { Code = "sm", Name = "YoWin" });
            services.TryAdd("zv", new ServiceItem { Code = "zv", Name = "Digikala" });
            services.TryAdd("bj", new ServiceItem { Code = "bj", Name = "Вита экспресс" });
            services.TryAdd("dv", new ServiceItem { Code = "dv", Name = "NoBroker" });
            services.TryAdd("zw", new ServiceItem { Code = "zw", Name = "Quack" });
            services.TryAdd("gh", new ServiceItem { Code = "gh", Name = "GyFTR" });
            services.TryAdd("cp", new ServiceItem { Code = "cp", Name = "Uklon" });
            services.TryAdd("ai", new ServiceItem { Code = "ai", Name = "CELEBe" });
            services.TryAdd("xf", new ServiceItem { Code = "xf", Name = "LightChat" });
            services.TryAdd("ym", new ServiceItem { Code = "ym", Name = "youla.ru" });
            services.TryAdd("ru", new ServiceItem { Code = "ru", Name = "HOP" });
            services.TryAdd("sj", new ServiceItem { Code = "sj", Name = "HandyPick" });
            services.TryAdd("fc", new ServiceItem { Code = "fc", Name = "PharmEasy" });
            services.TryAdd("hx", new ServiceItem { Code = "hx", Name = "AliExpress" });
            services.TryAdd("aw", new ServiceItem { Code = "aw", Name = "Taikang" });
            services.TryAdd("tx", new ServiceItem { Code = "tx", Name = "Bolt" });
            services.TryAdd("oh", new ServiceItem { Code = "oh", Name = "MapleSEA" });
            services.TryAdd("ki", new ServiceItem { Code = "ki", Name = "99app" });
            services.TryAdd("tg", new ServiceItem { Code = "tg", Name = "Telegram" });
            services.TryAdd("ug", new ServiceItem { Code = "ug", Name = "Fiqsy" });
            services.TryAdd("pq", new ServiceItem { Code = "pq", Name = "CDkeys" });
            services.TryAdd("gd", new ServiceItem { Code = "gd", Name = "Surveytime" });
            services.TryAdd("tc", new ServiceItem { Code = "tc", Name = "Rambler" });
            services.TryAdd("xw", new ServiceItem { Code = "xw", Name = "Taki" });
            services.TryAdd("oo", new ServiceItem { Code = "oo", Name = "LigaPro" });
            services.TryAdd("me", new ServiceItem { Code = "me", Name = "Line messenger" });
            services.TryAdd("of", new ServiceItem { Code = "of", Name = "Urent" });
            services.TryAdd("lz", new ServiceItem { Code = "lz", Name = "Things" });
            services.TryAdd("hd", new ServiceItem { Code = "hd", Name = "MarketPapa" });
            services.TryAdd("rm", new ServiceItem { Code = "rm", Name = "Faberlic" });
            services.TryAdd("ud", new ServiceItem { Code = "ud", Name = "Disney Hotstar" });
            services.TryAdd("eb", new ServiceItem { Code = "eb", Name = "Voltz" });
            services.TryAdd("wz", new ServiceItem { Code = "wz", Name = "FoxFord" });
            services.TryAdd("ur", new ServiceItem { Code = "ur", Name = "MyDailyCash" });
            services.TryAdd("jl", new ServiceItem { Code = "jl", Name = "Hopi" });
            services.TryAdd("gm", new ServiceItem { Code = "gm", Name = "Mocospace" });
            services.TryAdd("es", new ServiceItem { Code = "es", Name = "iQIYI" });
            services.TryAdd("zy", new ServiceItem { Code = "zy", Name = "Nttgame" });
            services.TryAdd("ef", new ServiceItem { Code = "ef", Name = "Nextdoor" });
            services.TryAdd("sk", new ServiceItem { Code = "sk", Name = "Skroutz" });
            services.TryAdd("sc", new ServiceItem { Code = "sc", Name = "Voggt" });
            services.TryAdd("fj", new ServiceItem { Code = "fj", Name = "Potato Chat" });
            services.TryAdd("mm", new ServiceItem { Code = "mm", Name = "Microsoft" });
            services.TryAdd("dy", new ServiceItem { Code = "dy", Name = "Zomato" });
            services.TryAdd("yi", new ServiceItem { Code = "yi", Name = "Yemeksepeti" });
            services.TryAdd("io", new ServiceItem { Code = "io", Name = "ЗдравСити" });
            services.TryAdd("jh", new ServiceItem { Code = "jh", Name = "PingPong" });
            services.TryAdd("gt", new ServiceItem { Code = "gt", Name = "Gett" });
            services.TryAdd("rp", new ServiceItem { Code = "rp", Name = "hamrahaval" });
            services.TryAdd("ei", new ServiceItem { Code = "ei", Name = "Taksheel" });
            services.TryAdd("co", new ServiceItem { Code = "co", Name = "Rediffmail" });
            services.TryAdd("fy", new ServiceItem { Code = "fy", Name = "Mylove" });
            services.TryAdd("un", new ServiceItem { Code = "un", Name = "humblebundle" });
            services.TryAdd("qj", new ServiceItem { Code = "qj", Name = "Whoosh" });
            services.TryAdd("nb", new ServiceItem { Code = "nb", Name = "Верный" });
            services.TryAdd("dx", new ServiceItem { Code = "dx", Name = "Powerkredite" });
            services.TryAdd("bz", new ServiceItem { Code = "bz", Name = "Blizzard" });
            services.TryAdd("wq", new ServiceItem { Code = "wq", Name = "Leboncoin1" });
            services.TryAdd("np", new ServiceItem { Code = "np", Name = "Siply" });
            services.TryAdd("re", new ServiceItem { Code = "re", Name = "Coinbase" });
            services.TryAdd("pr", new ServiceItem { Code = "pr", Name = "Trendyol" });
            services.TryAdd("wa", new ServiceItem { Code = "wa", Name = "Whatsapp" });
            services.TryAdd("fb", new ServiceItem { Code = "fb", Name = "facebook" });
            services.TryAdd("kd", new ServiceItem { Code = "kd", Name = "Author24" });
            services.TryAdd("gp", new ServiceItem { Code = "gp", Name = "Ticketmaster" });
            services.TryAdd("wo", new ServiceItem { Code = "wo", Name = "Parkplus" });
            services.TryAdd("up", new ServiceItem { Code = "up", Name = "Magnolia" });
            services.TryAdd("eq", new ServiceItem { Code = "eq", Name = "Qoo10" });
            services.TryAdd("ub", new ServiceItem { Code = "ub", Name = "Uber" });
            services.TryAdd("kb", new ServiceItem { Code = "kb", Name = "kufarby" });
            services.TryAdd("ig", new ServiceItem { Code = "ig", Name = "Instagram" });
            services.TryAdd("rh", new ServiceItem { Code = "rh", Name = "Ace2Three" });
            services.TryAdd("bc", new ServiceItem { Code = "bc", Name = "GCash" });
            services.TryAdd("hu", new ServiceItem { Code = "hu", Name = "Ukrnet" });
            services.TryAdd("pa", new ServiceItem { Code = "pa", Name = "Gamekit" });
            services.TryAdd("su", new ServiceItem { Code = "su", Name = "LOCO" });
            services.TryAdd("full", new ServiceItem { Code = "full", Name = "Full rent" });
            services.TryAdd("av", new ServiceItem { Code = "av", Name = "avito call forwarding" });
            services.TryAdd("ew", new ServiceItem { Code = "ew", Name = "Nike" });
            services.TryAdd("tw", new ServiceItem { Code = "tw", Name = "Twitter" });
            services.TryAdd("ry", new ServiceItem { Code = "ry", Name = "McDonalds" });
            services.TryAdd("cb", new ServiceItem { Code = "cb", Name = "Bazos" });
            services.TryAdd("yh", new ServiceItem { Code = "yh", Name = "hh" });
            services.TryAdd("lx", new ServiceItem { Code = "lx", Name = "DewuPoison" });
            services.TryAdd("ex", new ServiceItem { Code = "ex", Name = "Linode" });
            services.TryAdd("im", new ServiceItem { Code = "im", Name = "Imo" });
            services.TryAdd("kk", new ServiceItem { Code = "kk", Name = "Idealista" });
            services.TryAdd("ju", new ServiceItem { Code = "ju", Name = "Indomaret" });
            services.TryAdd("fv", new ServiceItem { Code = "fv", Name = "Vidio" });
            services.TryAdd("ue", new ServiceItem { Code = "ue", Name = "Onet" });
            services.TryAdd("jm", new ServiceItem { Code = "jm", Name = "mzadqatar" });
            services.TryAdd("rb", new ServiceItem { Code = "rb", Name = "Tick" });
            services.TryAdd("wj", new ServiceItem { Code = "wj", Name = "1хbet" });
            services.TryAdd("it", new ServiceItem { Code = "it", Name = "CashApp" });
            services.TryAdd("gu", new ServiceItem { Code = "gu", Name = "Fora" });
            services.TryAdd("eu", new ServiceItem { Code = "eu", Name = "LiveScore" });
            services.TryAdd("ff", new ServiceItem { Code = "ff", Name = "AVON" });
            services.TryAdd("qq", new ServiceItem { Code = "qq", Name = "Tencent QQ" });
            services.TryAdd("ty", new ServiceItem { Code = "ty", Name = "Окей" });
            services.TryAdd("dq", new ServiceItem { Code = "dq", Name = "IceCasino" });
            services.TryAdd("xq", new ServiceItem { Code = "xq", Name = "MPL" });
            services.TryAdd("wu", new ServiceItem { Code = "wu", Name = "PrivetMir" });
            services.TryAdd("jc", new ServiceItem { Code = "jc", Name = "IVI" });
            services.TryAdd("ha", new ServiceItem { Code = "ha", Name = "My11Circle" });
            services.TryAdd("ro", new ServiceItem { Code = "ro", Name = "PingCode" });
            services.TryAdd("sh", new ServiceItem { Code = "sh", Name = "Vkusvill" });
            services.TryAdd("tf", new ServiceItem { Code = "tf", Name = "Noon" });
            services.TryAdd("th", new ServiceItem { Code = "th", Name = "WestStein" });
            services.TryAdd("eo", new ServiceItem { Code = "eo", Name = "Sizeer" });
            services.TryAdd("ra", new ServiceItem { Code = "ra", Name = "KeyPay" });
            services.TryAdd("ny", new ServiceItem { Code = "ny", Name = "Pyro Music" });
            services.TryAdd("dn", new ServiceItem { Code = "dn", Name = "Paxful" });
            services.TryAdd("mv", new ServiceItem { Code = "mv", Name = "Fruitz" });
            services.TryAdd("ao", new ServiceItem { Code = "ao", Name = "UU163" });
            services.TryAdd("pl", new ServiceItem { Code = "pl", Name = "Перекресток" });
            services.TryAdd("nw", new ServiceItem { Code = "nw", Name = "Ximalaya" });
            services.TryAdd("qe", new ServiceItem { Code = "qe", Name = "GG" });
            services.TryAdd("sg", new ServiceItem { Code = "sg", Name = "OZON" });
            services.TryAdd("bu", new ServiceItem { Code = "bu", Name = "MonobankIndia" });
            services.TryAdd("af", new ServiceItem { Code = "af", Name = "GalaxyWin" });
            services.TryAdd("vw", new ServiceItem { Code = "vw", Name = "CoinField" });
            services.TryAdd("zl", new ServiceItem { Code = "zl", Name = "Airtel" });
            services.TryAdd("xp", new ServiceItem { Code = "xp", Name = "MonetaRu" });
            services.TryAdd("lf", new ServiceItem { Code = "lf", Name = "TikTok/Douyin" });
            services.TryAdd("cn", new ServiceItem { Code = "cn", Name = "Fiverr" });
            services.TryAdd("lv", new ServiceItem { Code = "lv", Name = "Megogo" });
            services.TryAdd("tp", new ServiceItem { Code = "tp", Name = "IndiaGold" });
            services.TryAdd("fx", new ServiceItem { Code = "fx", Name = "PGbonus" });
            services.TryAdd("pz", new ServiceItem { Code = "pz", Name = "Lidl" });
            services.TryAdd("pp", new ServiceItem { Code = "pp", Name = "Huya" });
            services.TryAdd("qk", new ServiceItem { Code = "qk", Name = "Bit" });
            services.TryAdd("jy", new ServiceItem { Code = "jy", Name = "Sorare" });
            services.TryAdd("rv", new ServiceItem { Code = "rv", Name = "Kotak811" });
            services.TryAdd("lg", new ServiceItem { Code = "lg", Name = "MediBuddy" });
            services.TryAdd("yl", new ServiceItem { Code = "yl", Name = "Yalla" });
            services.TryAdd("gq", new ServiceItem { Code = "gq", Name = "Freelancer" });
            services.TryAdd("xa", new ServiceItem { Code = "xa", Name = "УлыбкаРадуги" });
            services.TryAdd("ak", new ServiceItem { Code = "ak", Name = "Douyu" });
            services.TryAdd("sp", new ServiceItem { Code = "sp", Name = "HappyFresh" });
            services.TryAdd("vx", new ServiceItem { Code = "vx", Name = "HeyBox" });
            services.TryAdd("dc", new ServiceItem { Code = "dc", Name = "YikYak" });
            services.TryAdd("di", new ServiceItem { Code = "di", Name = "Loanflix" });
            services.TryAdd("bt", new ServiceItem { Code = "bt", Name = "Alfa" });
            services.TryAdd("wk", new ServiceItem { Code = "wk", Name = "Mobile01" });
            services.TryAdd("cx", new ServiceItem { Code = "cx", Name = "Icrypex" });
            services.TryAdd("yn", new ServiceItem { Code = "yn", Name = "Allegro" });
            services.TryAdd("fo", new ServiceItem { Code = "fo", Name = "MobiKwik" });
            services.TryAdd("ly", new ServiceItem { Code = "ly", Name = "Olacabs" });
            services.TryAdd("oi", new ServiceItem { Code = "oi", Name = "Tinder" });
            services.TryAdd("iz", new ServiceItem { Code = "iz", Name = "Global24" });
            services.TryAdd("nu", new ServiceItem { Code = "nu", Name = "Stripe" });
            services.TryAdd("fz", new ServiceItem { Code = "fz", Name = "KFC" });
            services.TryAdd("qi", new ServiceItem { Code = "qi", Name = "32red" });
            services.TryAdd("nv", new ServiceItem { Code = "nv", Name = "Naver" });
            services.TryAdd("op", new ServiceItem { Code = "op", Name = "MIRATORG" });
            services.TryAdd("wn", new ServiceItem { Code = "wn", Name = "GameArena" });
            services.TryAdd("dz", new ServiceItem { Code = "dz", Name = "Dominos Pizza" });
            services.TryAdd("vs", new ServiceItem { Code = "vs", Name = "WinzoGame" });
            services.TryAdd("rw", new ServiceItem { Code = "rw", Name = "BLS-SPAIN" });
            services.TryAdd("uq", new ServiceItem { Code = "uq", Name = "TopDetal" });
            services.TryAdd("fi", new ServiceItem { Code = "fi", Name = "Dundle" });
            services.TryAdd("bb", new ServiceItem { Code = "bb", Name = "LazyPay" });
            services.TryAdd("wc", new ServiceItem { Code = "wc", Name = "Craigslist" });
            services.TryAdd("vt", new ServiceItem { Code = "vt", Name = "Budget4me" });
            services.TryAdd("hn", new ServiceItem { Code = "hn", Name = "1688" });
            services.TryAdd("ps", new ServiceItem { Code = "ps", Name = "Zdorov" });
            services.TryAdd("da", new ServiceItem { Code = "da", Name = "MTS CashBack" });
            services.TryAdd("ja", new ServiceItem { Code = "ja", Name = "Weverse" });
            services.TryAdd("qu", new ServiceItem { Code = "qu", Name = "Agroinform" });
            services.TryAdd("jd", new ServiceItem { Code = "jd", Name = "GiraBank" });
            services.TryAdd("ay", new ServiceItem { Code = "ay", Name = "Ruten" });
            services.TryAdd("ym", new ServiceItem { Code = "ym", Name = "youla.ru call forwarding" });
            services.TryAdd("cr", new ServiceItem { Code = "cr", Name = "TenChat" });
            services.TryAdd("zo", new ServiceItem { Code = "zo", Name = "Kaggle" });
            services.TryAdd("dw", new ServiceItem { Code = "dw", Name = "Divar" });
            services.TryAdd("zk", new ServiceItem { Code = "zk", Name = "Deliveroo" });
            services.TryAdd("fh", new ServiceItem { Code = "fh", Name = "Lalamove" });
            services.TryAdd("nz", new ServiceItem { Code = "nz", Name = "Foodpanda" });
            services.TryAdd("nj", new ServiceItem { Code = "nj", Name = "FreshKarta" });
            services.TryAdd("yy", new ServiceItem { Code = "yy", Name = "Venmo" });
            services.TryAdd("rn", new ServiceItem { Code = "rn", Name = "neftm" });
            services.TryAdd("hi", new ServiceItem { Code = "hi", Name = "JungleeRummy" });
            services.TryAdd("oq", new ServiceItem { Code = "oq", Name = "Vlife" });
            services.TryAdd("tn", new ServiceItem { Code = "tn", Name = "LinkedIN" });
            services.TryAdd("kf", new ServiceItem { Code = "kf", Name = "Weibo" });
            services.TryAdd("hg", new ServiceItem { Code = "hg", Name = "Switips" });
            services.TryAdd("aq", new ServiceItem { Code = "aq", Name = "Glovo" });
            services.TryAdd("en", new ServiceItem { Code = "en", Name = "Hermes" });
            services.TryAdd("iw", new ServiceItem { Code = "iw", Name = "MyLavash" });
            services.TryAdd("ol", new ServiceItem { Code = "ol", Name = "KazanExpress" });
            services.TryAdd("dh", new ServiceItem { Code = "dh", Name = "eBay" });
            services.TryAdd("ta", new ServiceItem { Code = "ta", Name = "Wink" });
            services.TryAdd("tz", new ServiceItem { Code = "tz", Name = "Лейка" });
            services.TryAdd("nf", new ServiceItem { Code = "nf", Name = "Netflix" });
            services.TryAdd("mg", new ServiceItem { Code = "mg", Name = "Magnit" });
            services.TryAdd("gb", new ServiceItem { Code = "gb", Name = "YouStar" });
            services.TryAdd("pd", new ServiceItem { Code = "pd", Name = "IFood" });
            services.TryAdd("ni", new ServiceItem { Code = "ni", Name = "Gojek" });
            services.TryAdd("dt", new ServiceItem { Code = "dt", Name = "Delivery Club" });
            services.TryAdd("qm", new ServiceItem { Code = "qm", Name = "RosaKhutor" });
            services.TryAdd("qt", new ServiceItem { Code = "qt", Name = "MoneyСontrol" });
            services.TryAdd("ss", new ServiceItem { Code = "ss", Name = "hezzl" });
            services.TryAdd("rs", new ServiceItem { Code = "rs", Name = "Lotus" });
            services.TryAdd("uu", new ServiceItem { Code = "uu", Name = "Wildberries" });
            services.TryAdd("jp", new ServiceItem { Code = "jp", Name = "Rbt" });
            services.TryAdd("ce", new ServiceItem { Code = "ce", Name = "mosru" });
            services.TryAdd("ea", new ServiceItem { Code = "ea", Name = "JamesDelivery" });
            services.TryAdd("ti", new ServiceItem { Code = "ti", Name = "cryptocom" });
            services.TryAdd("td", new ServiceItem { Code = "td", Name = "ChaingeFinance" });
            services.TryAdd("yg", new ServiceItem { Code = "yg", Name = "CourseHero" });
            services.TryAdd("hr", new ServiceItem { Code = "hr", Name = "JKF" });
            services.TryAdd("kl", new ServiceItem { Code = "kl", Name = "kolesa.kz" });
            services.TryAdd("dj", new ServiceItem { Code = "dj", Name = "LUKOIL-AZS" });
            services.TryAdd("ql", new ServiceItem { Code = "ql", Name = "CMTcuzdan" });
            services.TryAdd("km", new ServiceItem { Code = "km", Name = "Rozetka" });
            services.TryAdd("jj", new ServiceItem { Code = "jj", Name = "Aitu" });
            services.TryAdd("vi", new ServiceItem { Code = "vi", Name = "Viber" });
            services.TryAdd("dl", new ServiceItem { Code = "dl", Name = "Lazada" });
            services.TryAdd("ll", new ServiceItem { Code = "ll", Name = "888casino" });
            services.TryAdd("nl", new ServiceItem { Code = "nl", Name = "Myntra" });
            services.TryAdd("sz", new ServiceItem { Code = "sz", Name = "Pivko24" });
            services.TryAdd("jx", new ServiceItem { Code = "jx", Name = "Swiggy" });
            services.TryAdd("ph", new ServiceItem { Code = "ph", Name = "SnappFood" });
            services.TryAdd("jn", new ServiceItem { Code = "jn", Name = "CloudBet" });
            services.TryAdd("le", new ServiceItem { Code = "le", Name = "E bike Gewinnspiel" });
            services.TryAdd("cz", new ServiceItem { Code = "cz", Name = "Getmega" });
            services.TryAdd("xm", new ServiceItem { Code = "xm", Name = "Лэтуаль" });
            services.TryAdd("ie", new ServiceItem { Code = "ie", Name = "bet365" });
            services.TryAdd("nq", new ServiceItem { Code = "nq", Name = "Trip" });
            services.TryAdd("kq", new ServiceItem { Code = "kq", Name = "FotoCasa" });
            services.TryAdd("zz", new ServiceItem { Code = "zz", Name = "DENT" });
            services.TryAdd("et", new ServiceItem { Code = "et", Name = "Clubhouse" });
            services.TryAdd("hh", new ServiceItem { Code = "hh", Name = "Uplay" });
            services.TryAdd("cm", new ServiceItem { Code = "cm", Name = "Prom" });
            services.TryAdd("uy", new ServiceItem { Code = "uy", Name = "Meliuz" });
            services.TryAdd("qr", new ServiceItem { Code = "qr", Name = "MEGA" });
            services.TryAdd("hq", new ServiceItem { Code = "hq", Name = "Magicbricks" });
            services.TryAdd("eg", new ServiceItem { Code = "eg", Name = "ContactSys" });
            services.TryAdd("rz", new ServiceItem { Code = "rz", Name = "EasyPay" });
            services.TryAdd("ut", new ServiceItem { Code = "ut", Name = "Энергобум" });
            services.TryAdd("yp", new ServiceItem { Code = "yp", Name = "Payzapp" });
            services.TryAdd("cl", new ServiceItem { Code = "cl", Name = "UWIN" });
            services.TryAdd("sa", new ServiceItem { Code = "sa", Name = "AGIBANK" });
            services.TryAdd("yk", new ServiceItem { Code = "yk", Name = "СпортМастер" });
            services.TryAdd("cd", new ServiceItem { Code = "cd", Name = "SpotHit" });
            services.TryAdd("wh", new ServiceItem { Code = "wh", Name = "TanTan" });
            services.TryAdd("ko", new ServiceItem { Code = "ko", Name = "AdaKami" });
            services.TryAdd("pf", new ServiceItem { Code = "pf", Name = "pof.com" });
            services.TryAdd("tv", new ServiceItem { Code = "tv", Name = "Flink" });
            services.TryAdd("yj", new ServiceItem { Code = "yj", Name = "eWallet" });
            services.TryAdd("gv", new ServiceItem { Code = "gv", Name = "Humta" });
            services.TryAdd("px", new ServiceItem { Code = "px", Name = "Nifty" });
            services.TryAdd("rc", new ServiceItem { Code = "rc", Name = "Skype" });
            services.TryAdd("ux", new ServiceItem { Code = "ux", Name = "Домовой" });
            services.TryAdd("so", new ServiceItem { Code = "so", Name = "RummyWealth" });
            services.TryAdd("bq", new ServiceItem { Code = "bq", Name = "Adani" });
            services.TryAdd("ob", new ServiceItem { Code = "ob", Name = "Onlinerby" });
            services.TryAdd("mq", new ServiceItem { Code = "mq", Name = "GMNG" });
            services.TryAdd("dm", new ServiceItem { Code = "dm", Name = "Iwplay" });
            services.TryAdd("kv", new ServiceItem { Code = "kv", Name = "Rush" });
            services.TryAdd("ms", new ServiceItem { Code = "ms", Name = "NovaPoshta" });
            services.TryAdd("yw", new ServiceItem { Code = "yw", Name = "Grindr" });
            services.TryAdd("ib", new ServiceItem { Code = "ib", Name = "Immowelt" });
            services.TryAdd("od", new ServiceItem { Code = "od", Name = "FWDMAX" });
            services.TryAdd("ip", new ServiceItem { Code = "ip", Name = "Burger King" });
            services.TryAdd("bh", new ServiceItem { Code = "bh", Name = "Uteka" });
            services.TryAdd("cw", new ServiceItem { Code = "cw", Name = "PTryAddyPower" });
            services.TryAdd("kz", new ServiceItem { Code = "kz", Name = "NimoTV" });
            services.TryAdd("uh", new ServiceItem { Code = "uh", Name = "Yubo" });
            services.TryAdd("fd", new ServiceItem { Code = "fd", Name = "Mamba" });
            services.TryAdd("qf", new ServiceItem { Code = "qf", Name = "RedBook" });
            services.TryAdd("qn", new ServiceItem { Code = "qn", Name = "Blued" });
            services.TryAdd("ix", new ServiceItem { Code = "ix", Name = "Celcoin" });
            services.TryAdd("my", new ServiceItem { Code = "my", Name = "CAIXA" });
            services.TryAdd("xe", new ServiceItem { Code = "xe", Name = "GalaxyChat" });
            services.TryAdd("fe", new ServiceItem { Code = "fe", Name = "CliQQ" });
            services.TryAdd("ax", new ServiceItem { Code = "ax", Name = "CrefisaMais" });
            services.TryAdd("kx", new ServiceItem { Code = "kx", Name = "Vivo" });
            services.TryAdd("ou", new ServiceItem { Code = "ou", Name = "Gabi" });
            services.TryAdd("sx", new ServiceItem { Code = "sx", Name = "Crowdtap" });
            services.TryAdd("tm", new ServiceItem { Code = "tm", Name = "Akulaku" });
            services.TryAdd("nt", new ServiceItem { Code = "nt", Name = "Sravni" });
            services.TryAdd("ct", new ServiceItem { Code = "ct", Name = "КухняНаРайоне" });
            services.TryAdd("kg", new ServiceItem { Code = "kg", Name = "FreeChargeApp" });
            services.TryAdd("ok", new ServiceItem { Code = "ok", Name = "ok.ru" });
            services.TryAdd("qx", new ServiceItem { Code = "qx", Name = "WorldRemit" });
            services.TryAdd("fq", new ServiceItem { Code = "fq", Name = "Контур" });
            services.TryAdd("ul", new ServiceItem { Code = "ul", Name = "Getir" });
            services.TryAdd("hf", new ServiceItem { Code = "hf", Name = "Cleartrip" });
            services.TryAdd("cf", new ServiceItem { Code = "cf", Name = "irancell" });
            services.TryAdd("vh", new ServiceItem { Code = "vh", Name = "Штолле" });
            services.TryAdd("rt", new ServiceItem { Code = "rt", Name = "hily" });
            services.TryAdd("gr", new ServiceItem { Code = "gr", Name = "Astropay" });
            services.TryAdd("tq", new ServiceItem { Code = "tq", Name = "Swvl" });
            services.TryAdd("oy", new ServiceItem { Code = "oy", Name = "CashFly" });
            services.TryAdd("ds", new ServiceItem { Code = "ds", Name = "Discord" });
            services.TryAdd("rf", new ServiceItem { Code = "rf", Name = "Akudo" });
            services.TryAdd("ui", new ServiceItem { Code = "ui", Name = "RuTube" });
            services.TryAdd("wt", new ServiceItem { Code = "wt", Name = "IZI" });
            services.TryAdd("xx", new ServiceItem { Code = "xx", Name = "Joyride" });
            services.TryAdd("df", new ServiceItem { Code = "df", Name = "Happn" });
            services.TryAdd("kn", new ServiceItem { Code = "kn", Name = "Verse" });
            services.TryAdd("oz", new ServiceItem { Code = "oz", Name = "Poshmark" });
            services.TryAdd("hb", new ServiceItem { Code = "hb", Name = "Twitch" });
            services.TryAdd("vj", new ServiceItem { Code = "vj", Name = "Stormgain" });
            services.TryAdd("ys", new ServiceItem { Code = "ys", Name = "ZCity" });
            services.TryAdd("dg", new ServiceItem { Code = "dg", Name = "Mercari" });
            services.TryAdd("uj", new ServiceItem { Code = "uj", Name = "СhampionСasino" });
            services.TryAdd("wx", new ServiceItem { Code = "wx", Name = "Apple" });
            services.TryAdd("jb", new ServiceItem { Code = "jb", Name = "Wing Money" });
            services.TryAdd("yx", new ServiceItem { Code = "yx", Name = "JTExpress" });
            services.TryAdd("gl", new ServiceItem { Code = "gl", Name = "GlobalTel" });
            services.TryAdd("ox", new ServiceItem { Code = "ox", Name = "Damejidlo" });
            services.TryAdd("po", new ServiceItem { Code = "po", Name = "premium.one" });
            services.TryAdd("ks", new ServiceItem { Code = "ks", Name = "Hirect" });
            services.TryAdd("iv", new ServiceItem { Code = "iv", Name = "Inboxlv" });
            services.TryAdd("gn", new ServiceItem { Code = "gn", Name = "A9A" });
            services.TryAdd("ft", new ServiceItem { Code = "ft", Name = "Букмекерские" });
            services.TryAdd("qy", new ServiceItem { Code = "qy", Name = "Zhihu" });
            services.TryAdd("st", new ServiceItem { Code = "st", Name = "Auchan" });
            services.TryAdd("bp", new ServiceItem { Code = "bp", Name = "GoFundMe" });
            services.TryAdd("xi", new ServiceItem { Code = "xi", Name = "InFund" });
            services.TryAdd("az", new ServiceItem { Code = "az", Name = "CityBase" });
            services.TryAdd("nc", new ServiceItem { Code = "nc", Name = "Payoneer" });
            services.TryAdd("py", new ServiceItem { Code = "py", Name = "Monese" });
            services.TryAdd("lq", new ServiceItem { Code = "lq", Name = "Potato" });
            services.TryAdd("js", new ServiceItem { Code = "js", Name = "GolosZa" });
            services.TryAdd("gx", new ServiceItem { Code = "gx", Name = "Hepsiburadacom" });
            services.TryAdd("vy", new ServiceItem { Code = "vy", Name = "Meta" });
            services.TryAdd("pv", new ServiceItem { Code = "pv", Name = "Koshelek" });
            services.TryAdd("va", new ServiceItem { Code = "va", Name = "SportGully" });
            services.TryAdd("el", new ServiceItem { Code = "el", Name = "Bisu" });
            services.TryAdd("wp", new ServiceItem { Code = "wp", Name = "163СOM" });
            services.TryAdd("lw", new ServiceItem { Code = "lw", Name = "MrGreen" });
            services.TryAdd("zs", new ServiceItem { Code = "zs", Name = "Bilibili" });
            services.TryAdd("yd", new ServiceItem { Code = "yd", Name = "米画师Mihuashi" });
            services.TryAdd("dp", new ServiceItem { Code = "dp", Name = "ProtonMail" });
            services.TryAdd("og", new ServiceItem { Code = "og", Name = "Okko" });
            services.TryAdd("vp", new ServiceItem { Code = "vp", Name = "Kwai" });
            services.TryAdd("ov", new ServiceItem { Code = "ov", Name = "Beget" });
            services.TryAdd("ls", new ServiceItem { Code = "ls", Name = "Careem" });
            services.TryAdd("xd", new ServiceItem { Code = "xd", Name = "Tokopedia" });
            services.TryAdd("hm", new ServiceItem { Code = "hm", Name = "Globus" });
            services.TryAdd("eh", new ServiceItem { Code = "eh", Name = "Telegram 2.0" });
            services.TryAdd("kc", new ServiceItem { Code = "kc", Name = "Vinted" });
            services.TryAdd("zt", new ServiceItem { Code = "zt", Name = "Budweiser" });
            services.TryAdd("fp", new ServiceItem { Code = "fp", Name = "Phound" });
            services.TryAdd("wd", new ServiceItem { Code = "wd", Name = "CasinoPlus" });
            services.TryAdd("ca", new ServiceItem { Code = "ca", Name = "SuperS" });
            services.TryAdd("ns", new ServiceItem { Code = "ns", Name = "Oldubil" });
            //services.TryAdd("ot", new ServiceItem { Code = "ot", Name = "Any other call forwarding" });
            services.TryAdd("zu", new ServiceItem { Code = "zu", Name = "BigC" });
            services.TryAdd("sn", new ServiceItem { Code = "sn", Name = "OLX" });
            services.TryAdd("lu", new ServiceItem { Code = "lu", Name = "Crickpe" });
            services.TryAdd("mi", new ServiceItem { Code = "mi", Name = "Zupee" });
            services.TryAdd("sb", new ServiceItem { Code = "sb", Name = "Lamoda" });
            services.TryAdd("pt", new ServiceItem { Code = "pt", Name = "Bitaqaty" });
            services.TryAdd("yv", new ServiceItem { Code = "yv", Name = "IPLwin" });
            services.TryAdd("tk", new ServiceItem { Code = "tk", Name = "МВидео" });
            services.TryAdd("ck", new ServiceItem { Code = "ck", Name = "BeReal" });
            services.TryAdd("lp", new ServiceItem { Code = "lp", Name = "Algida" });
            services.TryAdd("tu", new ServiceItem { Code = "tu", Name = "Lyft" });
            services.TryAdd("jo", new ServiceItem { Code = "jo", Name = "SticPay" });
            services.TryAdd("au", new ServiceItem { Code = "au", Name = "Haraj" });
            services.TryAdd("za", new ServiceItem { Code = "za", Name = "JDcom" });
            services.TryAdd("hw", new ServiceItem { Code = "hw", Name = "Alipay/Alibaba/1688" });
            services.TryAdd("ma", new ServiceItem { Code = "ma", Name = "Mail.ru" });
            services.TryAdd("pn", new ServiceItem { Code = "pn", Name = "CoffeeLike" });
            services.TryAdd("se", new ServiceItem { Code = "se", Name = "Feeld" });
            services.TryAdd("cs", new ServiceItem { Code = "cs", Name = "AgriDevelop" });
            services.TryAdd("vc", new ServiceItem { Code = "vc", Name = "Banqi" });
            services.TryAdd("uf", new ServiceItem { Code = "uf", Name = "Eneba" });
            services.TryAdd("lb", new ServiceItem { Code = "lb", Name = "Mailru Group" });
            services.TryAdd("iq", new ServiceItem { Code = "iq", Name = "icq" });
            services.TryAdd("nr", new ServiceItem { Code = "nr", Name = "Tosla" });
            services.TryAdd("os", new ServiceItem { Code = "os", Name = "Dhani" });
            services.TryAdd("xy", new ServiceItem { Code = "xy", Name = "Depop" });
            services.TryAdd("hp", new ServiceItem { Code = "hp", Name = "Meesho" });
            services.TryAdd("ml", new ServiceItem { Code = "ml", Name = "ApostaGanha" });
            services.TryAdd("hj", new ServiceItem { Code = "hj", Name = "Stoloto" });
            services.TryAdd("rk", new ServiceItem { Code = "rk", Name = "Fotka" });
            services.TryAdd("lo", new ServiceItem { Code = "lo", Name = "OPPO" });
            services.TryAdd("ez", new ServiceItem { Code = "ez", Name = "GoerliFaucet" });
            services.TryAdd("bf", new ServiceItem { Code = "bf", Name = "Keybase" });
            services.TryAdd("xb", new ServiceItem { Code = "xb", Name = "RummyOla" });
            services.TryAdd("sd", new ServiceItem { Code = "sd", Name = "dodopizza" });
            services.TryAdd("uk", new ServiceItem { Code = "uk", Name = "Airbnb" });
            services.TryAdd("ht", new ServiceItem { Code = "ht", Name = "Bitso" });
            services.TryAdd("vl", new ServiceItem { Code = "vl", Name = "Ортека" });
            services.TryAdd("ey", new ServiceItem { Code = "ey", Name = "miloan" });
            services.TryAdd("be", new ServiceItem { Code = "be", Name = "СберМегаМаркет" });
            services.TryAdd("ab", new ServiceItem { Code = "ab", Name = "Alibaba" });
            services.TryAdd("do", new ServiceItem { Code = "do", Name = "Leboncoin" });
            services.TryAdd("vr", new ServiceItem { Code = "vr", Name = "test" });
            services.TryAdd("zq", new ServiceItem { Code = "zq", Name = "IndiaPlays" });
            services.TryAdd("du", new ServiceItem { Code = "du", Name = "AUBANK" });
            services.TryAdd("ya", new ServiceItem { Code = "ya", Name = "Yandex" });
            services.TryAdd("gf", new ServiceItem { Code = "gf", Name = "GoogleVoice" });
            services.TryAdd("mz", new ServiceItem { Code = "mz", Name = "Zolushka" });
            services.TryAdd("mn", new ServiceItem { Code = "mn", Name = "RRSA" });
            services.TryAdd("nm", new ServiceItem { Code = "nm", Name = "Thisshop" });
            services.TryAdd("tt", new ServiceItem { Code = "tt", Name = "Ziglu" });
            services.TryAdd("rx", new ServiceItem { Code = "rx", Name = "Sheerid" });
            services.TryAdd("tl", new ServiceItem { Code = "tl", Name = "Truecaller" });
            services.TryAdd("ga", new ServiceItem { Code = "ga", Name = "Roposo" });
            services.TryAdd("jg", new ServiceItem { Code = "jg", Name = "Grab" });
            services.TryAdd("us", new ServiceItem { Code = "us", Name = "IRCTC" });
            services.TryAdd("xz", new ServiceItem { Code = "xz", Name = "paycell" });
            services.TryAdd("xk", new ServiceItem { Code = "xk", Name = "DiDi" });
            services.TryAdd("vz", new ServiceItem { Code = "vz", Name = "Hinge" });
            services.TryAdd("iy", new ServiceItem { Code = "iy", Name = "FoodHub" });
            services.TryAdd("yb", new ServiceItem { Code = "yb", Name = "Система Город" });
            services.TryAdd("wy", new ServiceItem { Code = "wy", Name = "Yami" });
            services.TryAdd("gi", new ServiceItem { Code = "gi", Name = "Hotline" });
            services.TryAdd("an", new ServiceItem { Code = "an", Name = "Adidas" });
            services.TryAdd("db", new ServiceItem { Code = "db", Name = "ezbuy" });
            services.TryAdd("mx", new ServiceItem { Code = "mx", Name = "SoulApp" });
            services.TryAdd("er", new ServiceItem { Code = "er", Name = "Kwork" });
            services.TryAdd("aj", new ServiceItem { Code = "aj", Name = "OneAset" });
            services.TryAdd("wm", new ServiceItem { Code = "wm", Name = "SMO71" });
            services.TryAdd("gj", new ServiceItem { Code = "gj", Name = "Carousell" });
            services.TryAdd("gc", new ServiceItem { Code = "gc", Name = "TradingView" });
            services.TryAdd("pb", new ServiceItem { Code = "pb", Name = "SkyTV" });
            services.TryAdd("ar", new ServiceItem { Code = "ar", Name = "Wondermart" });
            services.TryAdd("yf", new ServiceItem { Code = "yf", Name = "Citymobil" });
            services.TryAdd("uo", new ServiceItem { Code = "uo", Name = "CafeBazaar" });
            services.TryAdd("fx", new ServiceItem { Code = "fx", Name = "PGbonus call forwarding" });
            services.TryAdd("em", new ServiceItem { Code = "em", Name = "ZéDelivery" });
            services.TryAdd("qo", new ServiceItem { Code = "qo", Name = "Moneylion" });
            services.TryAdd("bo", new ServiceItem { Code = "bo", Name = "Wise" });
            services.TryAdd("mc", new ServiceItem { Code = "mc", Name = "Michat" });
            services.TryAdd("uv", new ServiceItem { Code = "uv", Name = "BinBin" });
            services.TryAdd("gw", new ServiceItem { Code = "gw", Name = "CallApp" });
            services.TryAdd("qz", new ServiceItem { Code = "qz", Name = "Faceit" });
            services.TryAdd("rr", new ServiceItem { Code = "rr", Name = "Wolt" });
            services.TryAdd("ws", new ServiceItem { Code = "ws", Name = "Indodax" });
            services.TryAdd("hz", new ServiceItem { Code = "hz", Name = "Drom" });
            services.TryAdd("ka", new ServiceItem { Code = "ka", Name = "Shopee" });
            services.TryAdd("yu", new ServiceItem { Code = "yu", Name = "Xiaomi" });
            services.TryAdd("ae", new ServiceItem { Code = "ae", Name = "myGLO" });
            services.TryAdd("ed", new ServiceItem { Code = "ed", Name = "Gamer" });
            services.TryAdd("uw", new ServiceItem { Code = "uw", Name = "Kirana" });
            services.TryAdd("bd", new ServiceItem { Code = "bd", Name = "X5ID" });
            services.TryAdd("kj", new ServiceItem { Code = "kj", Name = "YAPPY" });
            services.TryAdd("bk", new ServiceItem { Code = "bk", Name = "G2G" });
            services.TryAdd("xu", new ServiceItem { Code = "xu", Name = "RecargaPay" });
            services.TryAdd("mr", new ServiceItem { Code = "mr", Name = "Fastmail" });
            services.TryAdd("vd", new ServiceItem { Code = "vd", Name = "Betfair" });
            services.TryAdd("ve", new ServiceItem { Code = "ve", Name = "Dream11" });
            services.TryAdd("lt", new ServiceItem { Code = "lt", Name = "BitClout" });
            services.TryAdd("cq", new ServiceItem { Code = "cq", Name = "Mercado" });
            services.TryAdd("fs", new ServiceItem { Code = "fs", Name = "Şikayet var" });
            services.TryAdd("jw", new ServiceItem { Code = "jw", Name = "Br777" });
            services.TryAdd("br", new ServiceItem { Code = "br", Name = "Вкусно и Точка" });
            services.TryAdd("xr", new ServiceItem { Code = "xr", Name = "Tango" });
            services.TryAdd("xn", new ServiceItem { Code = "xn", Name = "Familia" });
            services.TryAdd("gg", new ServiceItem { Code = "gg", Name = "PagSmile" });
            services.TryAdd("ej", new ServiceItem { Code = "ej", Name = "MrQ" });
            services.TryAdd("ye", new ServiceItem { Code = "ye", Name = "ZaleyCash" });
            services.TryAdd("ec", new ServiceItem { Code = "ec", Name = "RummyCulture" });
            services.TryAdd("qs", new ServiceItem { Code = "qs", Name = "МирЗнакомств" });
            services.TryAdd("ep", new ServiceItem { Code = "ep", Name = "Temu" });
            services.TryAdd("yq", new ServiceItem { Code = "yq", Name = "Фокстрот" });
            services.TryAdd("cu", new ServiceItem { Code = "cu", Name = "炙热星河" });
            services.TryAdd("um", new ServiceItem { Code = "um", Name = "Belwest" });
            services.TryAdd("ri", new ServiceItem { Code = "ri", Name = "BillMill" });
            services.TryAdd("lk", new ServiceItem { Code = "lk", Name = "PurePlatfrom" });
            services.TryAdd("ij", new ServiceItem { Code = "ij", Name = "Revolut" });
            services.TryAdd("am", new ServiceItem { Code = "am", Name = "Amazon" });
            services.TryAdd("zg", new ServiceItem { Code = "zg", Name = "Setel" });
            services.TryAdd("bg", new ServiceItem { Code = "bg", Name = "MIXMART" });
            services.TryAdd("wb", new ServiceItem { Code = "wb", Name = "WeChat" });
            services.TryAdd("uz", new ServiceItem { Code = "uz", Name = "OffGamers" });
            services.TryAdd("qb", new ServiceItem { Code = "qb", Name = "Payberry" });
            services.TryAdd("il", new ServiceItem { Code = "il", Name = "IQOS" });
            services.TryAdd("ic", new ServiceItem { Code = "ic", Name = "JoGo" });
            services.TryAdd("tj", new ServiceItem { Code = "tj", Name = "dbrUA" });
            services.TryAdd("om", new ServiceItem { Code = "om", Name = "Corona" });
            services.TryAdd("mw", new ServiceItem { Code = "mw", Name = "Transfergo" });
            services.TryAdd("oc", new ServiceItem { Code = "oc", Name = "DealShare" });
            services.TryAdd("iu", new ServiceItem { Code = "iu", Name = "Bykea" });
            services.TryAdd("la", new ServiceItem { Code = "la", Name = "ssoidnet" });
            services.TryAdd("oe", new ServiceItem { Code = "oe", Name = "Codashop" });
            services.TryAdd("vg", new ServiceItem { Code = "vg", Name = "ShellBox" });
            services.TryAdd("uc", new ServiceItem { Code = "uc", Name = "Tatneft" });
            services.TryAdd("bv", new ServiceItem { Code = "bv", Name = "Metro" });
            services.TryAdd("de", new ServiceItem { Code = "de", Name = "Karusel" });
            services.TryAdd("je", new ServiceItem { Code = "je", Name = "Nanovest" });
            services.TryAdd("ah", new ServiceItem { Code = "ah", Name = "EscapeFromTarkov" });
            services.TryAdd("xh", new ServiceItem { Code = "xh", Name = "OVO" });
            services.TryAdd("wl", new ServiceItem { Code = "wl", Name = "YouGotaGift" });
            services.TryAdd("wr", new ServiceItem { Code = "wr", Name = "Walmart" });
            services.TryAdd("mt", new ServiceItem { Code = "mt", Name = "Steam" });
            services.TryAdd("fw", new ServiceItem { Code = "fw", Name = "99acres" });
            services.TryAdd("ev", new ServiceItem { Code = "ev", Name = "Picpay" });
            services.TryAdd("sq", new ServiceItem { Code = "sq", Name = "KuCoinPlay" });
            services.TryAdd("vn", new ServiceItem { Code = "vn", Name = "Yaay" });
            services.TryAdd("ba", new ServiceItem { Code = "ba", Name = "Expressmoney" });
            services.TryAdd("ww", new ServiceItem { Code = "ww", Name = "BIP" });
            services.TryAdd("cg", new ServiceItem { Code = "cg", Name = "Gemgala" });
            services.TryAdd("jz", new ServiceItem { Code = "jz", Name = "Kaya" });
            services.TryAdd("cv", new ServiceItem { Code = "cv", Name = "WashXpress" });
            services.TryAdd("ji", new ServiceItem { Code = "ji", Name = "Monobank" });
            services.TryAdd("si", new ServiceItem { Code = "si", Name = "Cita Previa" });
            services.TryAdd("xo", new ServiceItem { Code = "xo", Name = "Notifire" });
            services.TryAdd("aa", new ServiceItem { Code = "aa", Name = "Probo" });
            services.TryAdd("qa", new ServiceItem { Code = "qa", Name = "MyFishka" });
            services.TryAdd("vq", new ServiceItem { Code = "vq", Name = "LadyMaria" });
            services.TryAdd("vf", new ServiceItem { Code = "vf", Name = "Q12 Trivia" });
            services.TryAdd("lh", new ServiceItem { Code = "lh", Name = "24betting" });
            services.TryAdd("mh", new ServiceItem { Code = "mh", Name = "Ашан" });
            services.TryAdd("pw", new ServiceItem { Code = "pw", Name = "SellMonitor" });
            services.TryAdd("vb", new ServiceItem { Code = "vb", Name = "Кораблик" });
            services.TryAdd("rd", new ServiceItem { Code = "rd", Name = "Lenta" });
            services.TryAdd("xc", new ServiceItem { Code = "xc", Name = "SynotTip" });
            services.TryAdd("xv", new ServiceItem { Code = "xv", Name = "Wish" });
            services.TryAdd("li", new ServiceItem { Code = "li", Name = "Baidu" });
            services.TryAdd("yo", new ServiceItem { Code = "yo", Name = "Amasia" });
            services.TryAdd("lc", new ServiceItem { Code = "lc", Name = "Subito" });
            services.TryAdd("zd", new ServiceItem { Code = "zd", Name = "Zilch" });
            services.TryAdd("cj", new ServiceItem { Code = "cj", Name = "Dotz" });
            services.TryAdd("zi", new ServiceItem { Code = "zi", Name = "LoveLocal" });
            services.TryAdd("xt", new ServiceItem { Code = "xt", Name = "Flipkart" });
            services.TryAdd("mf", new ServiceItem { Code = "mf", Name = "Weidian" });
            services.TryAdd("pc", new ServiceItem { Code = "pc", Name = "Casino/bet/gambling" });
            services.TryAdd("mk", new ServiceItem { Code = "mk", Name = "LongHu" });
            services.TryAdd("mp", new ServiceItem { Code = "mp", Name = "Winmasters" });
            services.TryAdd("fm", new ServiceItem { Code = "fm", Name = "Touchance" });
            services.TryAdd("jf", new ServiceItem { Code = "jf", Name = "Likee" });
            services.TryAdd("kh", new ServiceItem { Code = "kh", Name = "Bukalapak" });
            services.TryAdd("we", new ServiceItem { Code = "we", Name = "DrugVokrug" });
            services.TryAdd("ho", new ServiceItem { Code = "ho", Name = "Cathay" });
            services.TryAdd("kw", new ServiceItem { Code = "kw", Name = "Foody" });
            services.TryAdd("ld", new ServiceItem { Code = "ld", Name = "Cashmine" });
            services.TryAdd("ts", new ServiceItem { Code = "ts", Name = "PayPal" });
            services.TryAdd("hl", new ServiceItem { Code = "hl", Name = "Band" });
            services.TryAdd("cy", new ServiceItem { Code = "cy", Name = "РСА" });
            services.TryAdd("ow", new ServiceItem { Code = "ow", Name = "RegRu" });
            services.TryAdd("xj", new ServiceItem { Code = "xj", Name = "СберМаркет" });
            services.TryAdd("nh", new ServiceItem { Code = "nh", Name = "AlloBank" });
            services.TryAdd("ku", new ServiceItem { Code = "ku", Name = "RoyalWin" });
            services.TryAdd("zn", new ServiceItem { Code = "zn", Name = "Biedronka" });
            services.TryAdd("xs", new ServiceItem { Code = "xs", Name = "GroupMe" });
            services.TryAdd("kr", new ServiceItem { Code = "kr", Name = "Eyecon" });
            services.TryAdd("ln", new ServiceItem { Code = "ln", Name = "Grofers" });
            services.TryAdd("lr", new ServiceItem { Code = "lr", Name = "Okta" });
            services.TryAdd("bw", new ServiceItem { Code = "bw", Name = "Signal" });
            services.TryAdd("ya", new ServiceItem { Code = "ya", Name = "Yandex" });
            services.TryAdd("zh", new ServiceItem { Code = "zh", Name = "Zoho" });
            services.TryAdd("ng", new ServiceItem { Code = "ng", Name = "FunPay" });
            services.TryAdd("fu", new ServiceItem { Code = "fu", Name = "Snapchat" });
            services.TryAdd("pu", new ServiceItem { Code = "pu", Name = "Justdating" });
            services.TryAdd("ky", new ServiceItem { Code = "ky", Name = "SpatenOktoberfest" });
            services.TryAdd("pj", new ServiceItem { Code = "pj", Name = "Podeli" });
            services.TryAdd("lm", new ServiceItem { Code = "lm", Name = "FarPost" });
            services.TryAdd("sw", new ServiceItem { Code = "sw", Name = "NCsoft" });
            services.TryAdd("go", new ServiceItem { Code = "go", Name = "Google,youtube,Gmail" });
            services.TryAdd("qd", new ServiceItem { Code = "qd", Name = "Taobao" });
        }

        public static ServiceItem? GetService(string code)
        {
            if (services.ContainsKey(code))
                return services[code];

            return null;
        }
        public static ServiceItem? FindSimilarServiceName(string input)
        {
            foreach (var service in services.Values)
                if (service.Name.ToUpper().Contains(input.ToUpper()))
                    return service;

            //return services["ot"];
            return null;
        }
        public static List<GetNumbersStatus> ParseServiceNumberStatus(string json)
        {
            if (!Extra.IsValidJson(json))
                throw new Exceptions.InvalidJsonException();

            var parsedList = new List<GetNumbersStatus>();
            var jsonObject = JObject.Parse(json);

            foreach (var property in jsonObject.Properties())
            {
                var propertyName = property.Name;
                var propertyValue = property.Value.ToString();

                var underscoreIndex = propertyName.LastIndexOf('_');
                if (underscoreIndex > 0)
                {
                    var serviceCode = propertyName[..underscoreIndex];
                    var forwarding = propertyName[(underscoreIndex + 1)..] == "1";

                    var serviceItem = GetService(serviceCode);
                    //var serviceItem = services[serviceCode];

                    var parsedService = new GetNumbersStatus
                    {
                        Service = serviceItem,
                        //Service = new ServiceItem
                        //{
                        //    Code = serviceItem.Code,
                        //    Name = serviceItem.Name
                        //},
                        Forwarding = forwarding,
                        Quantity = int.Parse(propertyValue)
                    };

                    parsedList.Add(parsedService);
                }
            }

            return parsedList;
        }
    }
}
